### PR TITLE
Commit task

### PR DESCRIPTION
**Pull request by TooDizzy**
Created a ```DockerCommitTask```that makes it possible to commit change to a running docker container.

### CODE REVIEW

**Comment by TooDizzy** [comment]
Hi,
Can see that the coverage report is not 100%. Sadly I can't access the report: https://coveralls.io/builds/9904552

**Comment by gesellix** [comment]
@TooDizzy low overall coverage is not an issue for you, that's my fault, so please ignore :-)
I'll have to have a look at your code later.

**Comment by TooDizzy** [comment]
Great. Let me know if there's any issues with the code.

Best regards / Med venlig hilsen
Tue S. Dissing

**Comment by gesellix** [comment]
@TooDizzy I merged your PR manually (https://github.com/gesellix/gradle-docker-plugin/commit/f1bec4378fa5c969b35fec4172192786f66e0372), as I made some smaller layout fixes. Thanks a lot for your contribution! The new release will be available in some minutes.

**Comment by TooDizzy** [comment]
Great to hear!

Best regards / Med venlig hilsen
Tue S. Dissing

**Pull request closed without merging**
